### PR TITLE
Update to the new jar name.

### PR DESCRIPTION
**Pull request by diamkil**
Fixes this docker downloading a corrupt jar because it fetches the incorrect URL

### CODE REVIEW

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/pterodactyl-stuff/blob/master/egg-geyser-m-c.json
shouldn't the default jar name be changed as well?

**Comment by diamkil** [comment]
Nope, I'm still making it save as Geyser.jar to avoid other changes, only the URL changes

**Comment by Camotoy** [comment]
Would it break if you changed it anyway?

**Comment by Kas-tle** [comment]
It wouldn't break it per se since the startup arguments would also be updated, so if someone did update the egg and run a reinstall, it would just download the new jar. If they didn't run a reinstall it would sort of break, but 1. It would be very obvious and 2. Assuming they took the manual step of downloading this egg file and uploading it, they would likely be aware of the change.

Also, I would recommend adding -L to all curl commands so that in the future redirect links will be followed (avoiding a situation like this where the egg no longer functions).

**Comment by Camotoy** [comment]
I'll merge this to get Docker working for now.

**Pull request merged**
