### PR TITLE
Update GeyserMC download URLs

### PR DESCRIPTION
**Pull request by PseudoResonance**
`target` in the artifact download URLs have been replaced with `build/libs` to match build system changes.

### CODE REVIEW

**Comment by onebeastchris** [comment]
https://discord.com/channels/613163671870242838/613167557184061459/1087108077892948059
as mentioned on the discord, we have a new downloads page for geyser now, and the ci is going to be deprecated at some point - could you change the links the the ones found on https://geysermc.org/download?

e.g. for spigot:
https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot

**Comment by PseudoResonance** [comment]
Everything except Geyser Connect now uses the new API and actually verifies the hash after downloading too.

Geyser Connect isn't available through the download API though.

**Comment by onebeastchris** [comment]
Nice, thanks! As for GeyserConnect - it's now a Geyser Extension, so to run GeyserConnect you'd use Geyser Standalone with the GeyserConnect extension. The download should get added to the downloads api soon enough; but for now, the GeyserConnect egg could be yeeted

**Comment by PseudoResonance** [comment]
What happened to the maintainers? Is this ever going to get merged?

**Comment by onebeastchris** [comment]
Sorry for the long wait. Unfortunately, the maintainer for this project currently doesnt have a pterodactyl setup to test these eggs. Personally, i just tried the Paper-Geyser-Floodgate one; while it starts up a paper server fine, it doesnt seem to be downloading/launching with either Geyser nor Floodgate. Could you test your PR? Thanks!

**Comment by PseudoResonance** [comment]
For some reason that egg was missing the mkdir plugins line. I've gone through and checked/tested them all again to make sure no others are like that. I also updated them to use the alpine installer which should speed up the installation process greatly.

**Comment by onebeastchris** [comment]
Hey, thanks for the quick response.
Now, most of the eggs work! 

A few things though:
- the velocity eggs crash due to a lack of forwarding-secret-file; which should be automatically generated by velocity :/
````[14:41:35 ERROR]: Unable to read/load/save your velocity.toml. The server will shut down.
java.lang.RuntimeException: The forwarding-secret-file does not exist.
        at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:502) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.VelocityServer.doStartupConfigLoad(VelocityServer.java:313) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:220) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
```

Then; the GeyserConnect egg does not work - GeyserConnect is no longer a standalone java program, and instead has to be hosted as a Geyser extension installed in Geyser Standalone (simply by putting the .jar into the extensions folder). 

Besides that; all other eggs now work! Thanks :)

As a sidenode: could be cool if it would be possible to specify the port Geyser runs on (now, even possible to do automatically with command line arguments - https://wiki.geysermc.org/geyser/geyser-command-line-arguments-and-system-properties/), although this is definitely outside of the scope of this PR.

**Comment by PseudoResonance** [comment]
I removed the downloading of the Velocity config, because it seems to break it, although it's still slightly broken, but that appears to be a Velocity bug.
I also replaced the GeyserConnect egg with the standalone one and had it download the latest build from Github actions, but because you can't download while unauthenticated, I had to use nightly.link to generate a download. A better solution would be to automatically publish build artifacts as Github releases and download those.
I also added the Geyser port variable to the applicable eggs.

**Comment by onebeastchris** [comment]
Tested the velocity and GeyserConnect egg, those indeed work now 👍 Also, thanks for the addition of the Geyser port setting - with these changes, eggs will be really useful now.
One slight issue though - "server" is not a valid entry in the new Geyser port field, since it requires an integer there. Other than that, the eggs (and setting the port) works perfectly :)

**Comment by PseudoResonance** [comment]
Ah whoops, I forgot about the server option. It's fixed now.

**Review by onebeastchris — APPROVED** [review]

**Pull request merged**
